FORMAT: 1A
HOST: http://lore.mit.edu/

# LORE

Simple API on top of MIT LORE application

# LORE API Root [/]

+ Parameters
    + repo_id: 1 (required, String) - ID of the Repository

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "learningobjects_url": "/repos/1/learningobjects",
            "taxonomy_url": "/repos/1/vocabularies",
            "members_url": "/repos/1/members",
        }

## Group Learning Objects

Learning Object resource

## LearningObjects [/repos/{repo_id}/learningobjects/{learningobject_id}]

+ Parameters
    + repo_id: 1 (required, String) - ID of the Repository
    + learningobject_id: 1 (required, String) - ID of the leanring object

## LearningObjects Collection [/repos/{repo_id}/learningobjects{?learning_resource_type%5b%5d*,course_id,xa_nr_views}]

+ Parameters
    + repo_id: 1 (required, String) - ID of the Repository
    + learning_resource_type: 1 (String) - types of learning resources

## Group Vocabularies


Resources related to Vocabularies in the API.

## Vocabulary [/repos/{repo_id}/vocabs/{vocab_id}]


+ Parameters
    + repo_id: 1 (required, String) - ID of the Repository
    + vocab_id: 1 (required, String) - ID of the Vocabulary

### View a Vocabulary [GET]

+ Response 200 (application/json)

        {
            "tbd": "tbd",
        }

## Term [/repos/{repo_id}/vocabs/{vocabs_id}/term/{term_id}]

+ Parameters
    + repo_id: 1 (required, String) - ID of the Repository
    + vocab_id: 1 (required, String) - ID of the Vocabulary
    + term_id: 1 (required, String) - ID of the Taxonomy term



## Vocabularies Collection [/repos/{repo_id}/vocabs/{?page}]

+ Parameters
    + repo_id: 1 (required, String) - ID of the Repository
    + page: 1 (optional, number) - The page of vocabularies to return

### List All Vocabularies [GET]

+ Response 200 (application/json)

    + Headers

            Link: </repos/1/vocabs?page=2>; rel="next"

    + Body

            [
                {
                    "tbd": "tbd",
                }
            ]

### Create a New Vocabulary [POST]

Create your own vocabulary by providing its JSON representation

+ Request (application/json)

        {
            "name": "learning objectives",
            "description": "learning objectives description",
            "vocabulary_type": "m"
            "weight": 1
            "learning_resource_types": [
                "Problem",
                "Vertical"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /repos/1/vocabularies/2

    + Body

            {
                "name": "learning objectives",
                "description": "learning objectives description",
                "vocabulary_type": "m"
                "weight": 1
                "learning_resource_types": [
                    "Problem",
                    "Vertical"
                ]
            }


## Group Members