FORMAT: 1A

# MIT LORE API documentation
NOTE: This document is **work in progress** 

# Group taxonomy

This section describes taxonomy api (vocabularies and terms) 

## Vocabulary Collection [/repos/{repo_id}/vocabularies]
Vocabulary is a collaction of taxonomy terms

+ Parameters
	+ repo_id: `1` (string) - The id of the Vocabulary

 
